# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-24 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
    ]
