# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190124_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='0', max_length=1),
        ),
    ]
